# Your MISP's URL
url: https://localhost

# The auth key to the MISP user that you wish to use. Make sure that the
# user has auth_key access
key:

# Should the certificate be validated?
verify_ssl: false

# The base directory for the outputs
output_dir: ./output

feeds:
    # Here begins the list of feeds to produce
    # The name of the feed
    - name: published

    # The number of entries to output
      entries: 10

    # The filters to be used for by the feed. You can use any filter that
    # you can use on the event index, such as organization, tags, etc.
    # It uses the same joining and condition rules as the API parameters
    # This example generates all published events
      filters:
        published: true

    # By default all attributes will be included in the feed generation
    # Remove the levels that you do not wish to include in the feed
    # Use this to further narrow down what gets exported, for example:
    # Setting this to ['3', '5'] will exclude any attributes from the feed that
    # are not exportable to all or inherit the event
    #
    # The levels are as follows:
    # 0: Your Organization Only
    # 1: This Community Only
    # 2: Connected Communities
    # 3: All
    # 4: Sharing Group
    # 5: Inherit Event
      valid_attribute_distribution_levels:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5

        # Apply any modifiers to the feed
      modifiers:
        # The specific modifier to apply, anonymize in this case
        # Each modifier will have their own configuration options
        - type: anonymize
          # The UUID to set the event org to
          uuid: 0d9264a8-67dd-41fc-a607-cabe96e0bcaf
          # The Name of the anonymized org
          name: Anon

      outputs:
        # Defines all the outputs you're like to send this feed to
        # Type is the output format to use
        # Each feed type will have their own configuration requirements
        - type: misp
          # The output directory relative to the global output_dir
          output_dir: published

        # You can even use the same feed multiple times
        - type: misp
          # The output directory relative to the global output_dir
          output_dir: published2

        # Silly output to screen
        - type: screen

    # Another example feed, that would generate a feed for all published events created by CIRCL,
    # tagged tlp:white and/or feed-export but exclude anything tagged privint
    - name: CIRCL
      output_dir: /circl
      entries: 200
      filters:
        tag: tlp:white|feed-export|!privint
        org: CIRCL
        published: true
      valid_attribute_distribution_levels:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5

      modifiers:
        - type: anonymize
          uuid: 0d9264a8-67dd-41fc-a607-cabe96e0bcaf
          name: Anon

      outputs:
        - type: misp
          output_dir: circl
        - type: screen

