version: '3'
services:

  misp-feedgen:
    image: coolacid/misp-feedgen:latest
    build: .
    volumes:
      - "./config.yml:/srv/misp-feedgen/config.yml:ro"
    entrypoint: ./generate.py config.yml -a
